name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@136412a57a7081aa63c935a2cc2918f76c34f514 # v1
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ vars.APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'ssh-agent-deploy-key'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@d385c88822a237acaead89c462fa0aef7502748f # v41.0.11
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '^npm '
          RENOVATE_AUTODISCOVER: 'true'
