name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ vars.APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'ssh-agent-deploy-key'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e02bf7b1c996027e55e910400653576a8293246c # v41.0.3
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '^npm '
          RENOVATE_AUTODISCOVER: 'true'
