name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ vars.APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'ssh-agent-deploy-key'
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@7743ec9e19ceeb61a3862c5d4131e6710195af11 # v40.3.3
        with:
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '^npm '
          RENOVATE_AUTODISCOVER: 'true'
