name: 'build-test'
on:
  # use PR target so that we run in the context of
  # this repo so that the secrets used in the tests
  # are accessible
  pull_request_target:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
      - uses: codecov/codecov-action@v3
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          ssh-private-key: |
            ${{ secrets.ED25519_KEY }}
            bad key
            ${{ secrets.ED25519_DEPLOY }}
            ${{ secrets.RSA_KEY }}
            trash-string
            ${{ secrets.RSA_DEPLOY }}
            ${{ secrets.ECDSA_KEY }}
            ${{ secrets.ECDSA_DEPLOY }}

      - name: Show configs
        run: |
          [ -f $HOME/.gitconfig ] && cat $HOME/.gitconfig || :
          [ -f $HOME/.ssh/config ] && cat $HOME/.ssh/config || :
